-- PostgreSQL (Supabase) semasi. SQLite'taki 001..004 migration'larinin toplami; ayni tablolar ve kurallar.
-- Bulut veritabani sifirdan kuruldugu icin tek dosya yeterli. Bundan sonraki her sema degisikligi
-- HEM migrations/00N_*.sql (SQLite) HEM migrations/postgres/00N_*.sql olarak yazilir.
--
-- SQLite'tan farklar:
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--   COLLATE NOCASE (e-posta)          -> lower(email) uzerinde UNIQUE indeks
--   vector BLOB                        -> pgvector "vector" tipi (benzerlik aramasi SQL'de yapilir)
--   created_at                         -> SQLite ile ayni metin bicimi ('YYYY-MM-DD HH:MM:SS', UTC);
--                                         boylece rapor ve arayuz kodu iki veritabaninda ayni calisir
--   ROW LEVEL SECURITY                 -> Supabase, public semadaki tablolari kendi REST API'siyle de sunar.
--                                         RLS acik + hic politika yok = o API'den kimse okuyamaz/yazamaz.
--                                         Uygulamamiz tablo sahibi (postgres) olarak baglandigi icin etkilenmez.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX users_email_unique ON users (lower(email));

CREATE TABLE documents (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename    TEXT NOT NULL,
    stored_name TEXT,
    mime_type   TEXT,
    size_bytes  BIGINT NOT NULL DEFAULT 0,
    status      TEXT NOT NULL DEFAULT 'uploaded'
                CHECK (status IN ('uploaded', 'chunked', 'indexed', 'failed')),
    error       TEXT,
    uploaded_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX idx_documents_user ON documents(user_id);

CREATE TABLE chunks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content     TEXT NOT NULL,
    page_no     INTEGER,
    UNIQUE (document_id, chunk_index)
);

-- Boyut (384, 1024 ...) modele gore degisir; sabitlenmedigi icin indeks yok, arama tam taramadir.
-- Ogrenci projesi boyutunda (birkac bin parca) milisaniyeler surer. Cok buyurse: vector(384) + HNSW indeksi.
CREATE TABLE embeddings (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id INTEGER NOT NULL UNIQUE REFERENCES chunks(id) ON DELETE CASCADE,
    vector   vector NOT NULL,
    dim      INTEGER NOT NULL,
    model    TEXT NOT NULL
);

CREATE TABLE conversations (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title        TEXT NOT NULL DEFAULT 'Yeni sohbet',
    created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    summary      TEXT,
    summary_upto INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_conversations_user ON conversations(user_id);

CREATE TABLE messages (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT NOT NULL,
    created_at      TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    status          TEXT,
    grounded        INTEGER,
    latency_ms      INTEGER,
    best_score      DOUBLE PRECISION
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);

CREATE TABLE message_sources (
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    chunk_id   INTEGER NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
    score      DOUBLE PRECISION,
    n          INTEGER,
    PRIMARY KEY (message_id, chunk_id)
);
CREATE INDEX idx_message_sources_chunk ON message_sources(chunk_id);

CREATE TABLE password_resets (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash  TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    attempts   INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);
CREATE INDEX idx_password_resets_user ON password_resets(user_id);

ALTER TABLE users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents       ENABLE ROW LEVEL SECURITY;
ALTER TABLE chunks          ENABLE ROW LEVEL SECURITY;
ALTER TABLE embeddings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages        ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_resets ENABLE ROW LEVEL SECURITY;
