-- PostgreSQL karsiligi: migrations/005_name_and_email_verification.sql (aciklamalar orada).
-- Ad soyad + e-posta dogrulama; password_resets -> email_codes (purpose: verify | reset).

ALTER TABLE users ADD COLUMN full_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email_verified_at TEXT;
UPDATE users SET email_verified_at = created_at;

CREATE TABLE email_codes (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose    TEXT NOT NULL CHECK (purpose IN ('verify', 'reset')),
    code_hash  TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    attempts   INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);
CREATE INDEX idx_email_codes_user ON email_codes(user_id, purpose);
ALTER TABLE email_codes ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS password_resets;
