-- PostgreSQL karsiligi: migrations/006_api_tokens.sql (aciklamalar orada).
-- Kisisel API anahtarlari: anahtarin kendisi degil, SHA-256 ozeti saklanir.

CREATE TABLE api_tokens (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    prefix       TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    last_used_at TEXT,
    expires_at   TEXT NOT NULL
);
CREATE INDEX idx_api_tokens_user ON api_tokens(user_id);
ALTER TABLE api_tokens ENABLE ROW LEVEL SECURITY;
